import { index, pgTable, text, timestamp, unique, uuid, varchar } from 'drizzle-orm/pg-core';
import { createdAt } from './_shared';
import { users } from './users';

/**
 * In-app notifications generated by the daily cron.
 * recipientUserId nullable = broadcast to any staff. dedupKey prevents the cron
 * from creating duplicate notifications on repeat runs (e.g. same ad, same threshold).
 */
export const notifications = pgTable(
  'notifications',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    recipientUserId: uuid('recipient_user_id').references(() => users.id),
    category: text('category', {
      enum: [
        'AD_EXPIRING',
        'IMMIGRATION_EXPIRING',
        'TASK_OVERDUE',
        'PAYMENT_PENDING',
        'FOLLOW_UP_DUE',
      ],
    }).notNull(),
    title: varchar('title', { length: 255 }).notNull(),
    body: text('body'),
    entityType: varchar('entity_type', { length: 80 }),
    entityId: uuid('entity_id'),
    href: varchar('href', { length: 500 }),
    /** Idempotency key — dedup within a category + entity + threshold bucket. */
    dedupKey: varchar('dedup_key', { length: 255 }).notNull(),
    createdAt,
    readAt: timestamp('read_at', { withTimezone: true }),
  },
  (t) => [
    unique('notifications_dedup_unique').on(t.dedupKey),
    index('notifications_recipient_idx').on(t.recipientUserId, t.createdAt),
    index('notifications_unread_idx').on(t.readAt),
  ],
);

export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;
